sonar.projectKey=plexsalud
sonar.projectName=plexsalud
sonar.sourceEncoding=UTF-8
sonar.sources=plexsalud/src/
sonar.exclusions=**/*.spec.ts,**/*.module.ts,**/environments/**
sonar.tests=plexsalud/src/
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=plexsalud/coverage/lcov.info
